spring:
  profiles:
    active: local
---
spring:
  batch:
    job:
      enabled: false
    initialize-schema: always
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3307/spring_batch
      username: root
      password: test
      driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  profiles: dev
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://15.165.236.202:3306/spaces
      username: root
      password: q4jHwPMv
      driver-class-name: com.mysql.cj.jdbc.Driver